data:
  dataset:
    train_path: data/SQuAD/train-v1.1.json
    dev_path: data/SQuAD/dev-v1.1.json
  dataset_h5: data/squad_glove.h5

  embedding_path: data/glove.840B.300d.zip

  model_path: data/model-weight.pt
  checkpoint_path: data/checkpoint

global:
  random_seed: 123
  num_data_workers: 5   # for data loader
  model: match-lstm+  # 'match-lstm', 'match-lstm+', 'r-net', 'm-reader' or 'base'
                      # Note that 'base' model is customized by base_model.yaml

preprocess:
  word_embedding_size: 300
  ignore_max_len: 600 # in train data, context token len > ignore_max_len will be dropped
  use_char: True
  use_pos: True
  use_ent: True
  use_em: True
  use_em_lemma: True

train:
  batch_size: 32
  valid_batch_size: 32
  epoch: 30
  enable_cuda: True

  optimizer: 'adamax'  # adam, sgd, adamax, adadelta(default is adamax)
  learning_rate: 0.002  # only for sgd
  clip_grad_norm: 5

test:
  batch_size: 32
  enable_cuda: True