data:
  dataset:
    train_path: data/SQuAD/train-v1.1.json
    dev_path: data/SQuAD/dev-v1.1.json
  dataset_h5: data/squad_glove.h5

  embedding_path: data/glove.840B.300d.zip

  model_path: data/model-weight.pt
  checkpoint_path: data/checkpoint

model:
  embedding_size: 300
  hidden_size: 150  # one-direction
  encoder_bidirection: False
  encoder_char: False

train:
  batch_size: 32
  epoch: 30
  enable_cuda: False
  random_seed: 123

  optimizer: 'adamax'  # adam, sgd, adamax, (default is adamax)
  adamax_beta1: 0.9
  adamax_beta2: 0.999
  learning_rate: 0.002

test:
  batch_size: 32
  enable_cuda: False
  random_seed: 123