data:
  dataset:
    train_path: data/SQuAD/train-v1.1.json
    dev_path: data/SQuAD/dev-v1.1.json
  dataset_h5: data/squad_glove.h5

  embedding_path: data/glove.840B.300d.zip

  model_path: data/model-weight.pt
  checkpoint_path: data/checkpoint

model:
  random_seed: 123
  dropout_p: 0.4

  embedding_size: 300
  hidden_size: 45  # one-direction

  encoder_word_layers: 3
  encoder_char_layers: 1
  encoder_bidirection: True
  encoder_char: False

  match_lstm_bidirection: True
  self_match_lstm_bidirection: True
  self_match_lstm: True

  birnn_after_self: True
  init_ptr_hidden: pooling # pooling, linear, None
  answer_search: True

  hidden_mode: GRU # LSTM or GRU
  gated_attention: True

train:
  batch_size: 32
  valid_batch_size: 32
  epoch: 30
  enable_cuda: False

  optimizer: 'adadelta'  # adam, sgd, adamax, adadelta(default is adamax)
  learning_rate: 0.002  # only for sgd
  clip_grad_norm: 5

test:
  batch_size: 32
  enable_cuda: False