data:
  dataset:
    train_path: data/SQuAD/train-v1.1.json
    dev_path: data/SQuAD/dev-v1.1.json
  dataset_h5: data/squad.h5

  embedding_path: data/glove.840B.300d.zip
  embedding_h5: data/glove.840B.300d.h5

  model_path: data/model-weight.pt

model:
  embedding_size: 300
  hidden_size: 150  # one-direction

train:
  batch_size: 30
  epoch: 50
  enable_cuda: True

  optimizer: 'adam'  # adam, sgd, adamax
  adamax_beta1: 0.9
  adamax_beta2: 0.999
  learning_rate: 0.002
